fragment LoyaltyBalance on LoyaltyBalance {
  points
  tier
  tierName
  tierMultiplier
  lifetimePoints
  nextTier {
    slug
    name
    minPoints
    multiplier
  }
  nextTierPoints
  referralCode
}
