query GetEcontOffices($city: String, $search: String) {
  econtOffices(city: $city, search: $search) {
    id
    code
    name
    nameEn
    address
    city
    postCode
    latitude
    longitude
    workingTimeFrom
    workingTimeTo
    workingTimeHalfFrom
    workingTimeHalfTo
  }
}
