mutation SaveEcontOffice(
  $orderId: Int!
  $officeCode: String!
  $officeName: String
  $officeAddress: String
  $officeCity: String
) {
  saveEcontOfficeToOrder(
    input: {
      orderId: $orderId
      officeCode: $officeCode
      officeName: $officeName
      officeAddress: $officeAddress
      officeCity: $officeCity
    }
  ) {
    success
    message
  }
}
